import { createFileRoute } from '@tanstack/react-router'
import { createChatHandler } from '@tanstack/framework/handler'
import { getChatProvider } from '@tanstack/framework/chat'
import { resolvePersona } from '@tanstack/framework/chat'

// Auto-discovered tools from src/tools/ (generated by @tanstack/framework)
import { toolList } from '../__generated__/tool-registry.gen'


// Combine all tools
const allTools = [
  ...toolList,
]

// Create the handler with all configuration
const chatHandler = createChatHandler({
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  tools: allTools as any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  provider: getChatProvider as any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  resolvePersona: resolvePersona as any,
})

export const Route = createFileRoute('/api/chat')({
  server: {
    handlers: {
      POST: async ({ request }) => chatHandler(request),
    },
  },
})
