/**
 * Durable Chat API Route
 *
 * This route uses the durable chat handler which provides:
 * - Pull-based streaming with LSN for reconnection
 * - Session management via SessionRegistry
 * - Multi-client fan-out from shared buffer
 *
 * Protocol:
 * - Request headers: X-Session-Id (optional), X-Last-LSN (optional)
 * - Response: NDJSON with {lsn, event} per line
 * - Response headers: X-Session-Id
 */
import { createFileRoute } from '@tanstack/react-router'
import { createDurableChatHandler } from '@tanstack/framework/handler/durable'
import { setupInMemoryDurableStreams } from '@tanstack/framework/chat/durable-streams'
import { resolvePersona, ollamaProvider, openaiProvider } from '@tanstack/framework/chat'
import {
  ProviderContext,
  ToolRegistryContext,
  PersonaResolverContext,
  MaxIterationsContext,
} from '@tanstack/framework/chat'
import type { Operation } from 'effection'
import type { InitializerContext } from '@tanstack/framework/handler/durable'
import { env } from '@/env'

// Auto-discovered tools from src/tools/ (generated by @tanstack/framework)
import { toolList } from '../__generated__/tool-registry.gen'

// Combine all tools
const allTools = [...toolList]

// Initializer hooks for durable handler
const setupDurableStreams = function* (): Operation<void> {
  // Set up in-memory durable streams infrastructure
  // In production, could use Redis or other persistent stores
  yield* setupInMemoryDurableStreams<string>()
}

const setupProvider = function* (ctx: InitializerContext): Operation<void> {
  // Dynamic provider selection based on request
  const providerName = ctx.body.provider || env.CHAT_PROVIDER
  const providerMap = {
    ollama: ollamaProvider,
    openai: openaiProvider,
  }

  const selectedProvider = providerMap[providerName as keyof typeof providerMap]
  if (!selectedProvider) {
    throw new Error(`Unknown provider: ${providerName}`)
  }

  yield* ProviderContext.set(selectedProvider)
}

const setupTools = function* (_ctx: InitializerContext): Operation<void> {
  yield* ToolRegistryContext.set(allTools)
}

const setupPersonaResolver = function* (_ctx: InitializerContext): Operation<void> {
  yield* PersonaResolverContext.set(resolvePersona)
}

const setupMaxIterations = function* (_ctx: InitializerContext): Operation<void> {
  yield* MaxIterationsContext.set(10)
}

// Create the durable handler with hook-based configuration
const durableChatHandler = createDurableChatHandler({
  initializerHooks: [
    setupDurableStreams,
    setupProvider,
    setupTools,
    setupPersonaResolver,
    setupMaxIterations,
  ],
})

export const Route = createFileRoute('/api/durable-chat')({
  server: {
    handlers: {
      POST: async ({ request }) => {
        return durableChatHandler(request)
      },
    },
  },
})
