/**
 * Durable Chat API Route
 *
 * Uses the new durable streaming handler for:
 * - Session reconnection from last LSN
 * - Multi-client fan-out
 * - Full session replay
 *
 * This route is API-compatible with /api/chat but adds durability features.
 */
import { createFileRoute } from '@tanstack/react-router'
import { createDurableChatHandler, type InitializerContext } from '@tanstack/framework/handler/durable'
import { setupInMemoryDurableStreams } from '@tanstack/framework/chat/durable-streams'
import { resolvePersona, ollamaProvider, openaiProvider } from '@tanstack/framework/chat'
import { ProviderContext, ToolRegistryContext, PersonaResolverContext, MaxIterationsContext } from '@tanstack/framework/chat'
import type { Operation } from 'effection'
import { env } from "@/env"

// Auto-discovered tools from src/tools/ (generated by @tanstack/framework)
import { toolList } from '../__generated__/tool-registry.gen'

// Combine all tools
const allTools = [
  ...toolList,
]

// Initializer hook to setup durable streams infrastructure
const setupDurableStreamsHook = function*(_ctx: InitializerContext): Operation<void> {
  console.log('[durable-hook] Setting up in-memory durable streams...')
  // Setup in-memory durable streams (creates registry + stores + sets contexts)
  yield* setupInMemoryDurableStreams<string>()
  console.log('[durable-hook] Durable streams setup complete')
}

// Initializer hooks
const setupProvider = function*(ctx: InitializerContext): Operation<void> {
  console.log('[durable-hook] Setting up provider...')
  // Dynamic provider selection based on request
  const providerName = ctx.body.provider || env.CHAT_PROVIDER
  const providerMap = {
    ollama: ollamaProvider,
    openai: openaiProvider,
  }

  const selectedProvider = providerMap[providerName as keyof typeof providerMap]
  if (!selectedProvider) {
    throw new Error(`Unknown provider: ${providerName}`)
  }

  yield* ProviderContext.set(selectedProvider)
  console.log('[durable-hook] Provider set:', providerName)
}

const setupTools = function*(_ctx: InitializerContext): Operation<void> {
  // Could be dynamic based on request, e.g., filter tools by enabledTools
  yield* ToolRegistryContext.set(allTools)
}

const setupPersonaResolver = function*(_ctx: InitializerContext): Operation<void> {
  yield* PersonaResolverContext.set(resolvePersona)
}

const setupMaxIterations = function*(_ctx: InitializerContext): Operation<void> {
  yield* MaxIterationsContext.set(10)
}

// Create the handler with hook-based configuration
// IMPORTANT: setupDurableStreamsHook must run first to set up the registry context
const durableChatHandler = createDurableChatHandler({
  initializerHooks: [
    setupDurableStreamsHook,
    setupProvider,
    setupTools,
    setupPersonaResolver,
    setupMaxIterations,
  ],
})

export const Route = createFileRoute('/api/chat-durable')({
  server: {
    handlers: {
      POST: async ({ request }) => {
        return durableChatHandler(request)
      },
    },
  },
})
