import { createFileRoute } from '@tanstack/react-router'
import { createChatHandler, type InitializerContext } from '@tanstack/framework/handler'
import { resolvePersona, ollamaProvider, openaiProvider } from '@tanstack/framework/chat'
import { ProviderContext, ToolRegistryContext, PersonaResolverContext, MaxIterationsContext } from '@tanstack/framework/chat'
import type { Operation } from 'effection'
import { env } from "@/env"

// Auto-discovered tools from src/tools/ (generated by @tanstack/framework)
import { toolList } from '../__generated__/tool-registry.gen'

// Combine all tools
const allTools = [
  ...toolList,
]

// Initializer hooks
const setupProvider = function*(ctx: InitializerContext): Operation<void> {
  // Dynamic provider selection based on request
  const providerName = ctx.body.provider || env.CHAT_PROVIDER
  const providerMap = {
    ollama: ollamaProvider,
    openai: openaiProvider,
  }

  const selectedProvider = providerMap[providerName as keyof typeof providerMap]
  console.log({ selectedProvider })
  if (!selectedProvider) {
    throw new Error(`Unknown provider: ${providerName}`)
  }

  yield* ProviderContext.set(selectedProvider)
}

const setupTools = function*(ctx: InitializerContext): Operation<void> {
  // Could be dynamic based on request, e.g., filter tools by enabledTools
  yield* ToolRegistryContext.set(allTools)
}

const setupPersonaResolver = function*(ctx: InitializerContext): Operation<void> {
  yield* PersonaResolverContext.set(resolvePersona)
}

const setupMaxIterations = function*(ctx: InitializerContext): Operation<void> {
  yield* MaxIterationsContext.set(10)
}

// Create the handler with hook-based configuration
const chatHandler = createChatHandler({
  initializerHooks: [setupProvider, setupTools, setupPersonaResolver, setupMaxIterations],
})

export const Route = createFileRoute('/api/chat')({
  server: {
    handlers: {
      POST: async ({ request }) => {
        // Use simple handler for now to test basic functionality
        return chatHandler(request)
      },
    },
  },
})
