/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHelloStreamRouteImport } from './routes/api.hello-stream'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as DemoTicTacToeIndexRouteImport } from './routes/demo/tic-tac-toe/index'
import { Route as DemoMathIndexRouteImport } from './routes/demo/math/index'
import { Route as DemoChatIndexRouteImport } from './routes/demo/chat/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloStreamRoute = ApiHelloStreamRouteImport.update({
  id: '/api/hello-stream',
  path: '/api/hello-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTicTacToeIndexRoute = DemoTicTacToeIndexRouteImport.update({
  id: '/demo/tic-tac-toe/',
  path: '/demo/tic-tac-toe/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMathIndexRoute = DemoMathIndexRouteImport.update({
  id: '/demo/math/',
  path: '/demo/math/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChatIndexRoute = DemoChatIndexRouteImport.update({
  id: '/demo/chat/',
  path: '/demo/chat/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/demo/chat': typeof DemoChatIndexRoute
  '/demo/math': typeof DemoMathIndexRoute
  '/demo/tic-tac-toe': typeof DemoTicTacToeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/demo/chat': typeof DemoChatIndexRoute
  '/demo/math': typeof DemoMathIndexRoute
  '/demo/tic-tac-toe': typeof DemoTicTacToeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/demo/chat/': typeof DemoChatIndexRoute
  '/demo/math/': typeof DemoMathIndexRoute
  '/demo/tic-tac-toe/': typeof DemoTicTacToeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/demo/chat'
    | '/demo/math'
    | '/demo/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/demo/chat'
    | '/demo/math'
    | '/demo/tic-tac-toe'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/demo/chat/'
    | '/demo/math/'
    | '/demo/tic-tac-toe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHelloStreamRoute: typeof ApiHelloStreamRoute
  DemoChatIndexRoute: typeof DemoChatIndexRoute
  DemoMathIndexRoute: typeof DemoMathIndexRoute
  DemoTicTacToeIndexRoute: typeof DemoTicTacToeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello-stream': {
      id: '/api/hello-stream'
      path: '/api/hello-stream'
      fullPath: '/api/hello-stream'
      preLoaderRoute: typeof ApiHelloStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tic-tac-toe/': {
      id: '/demo/tic-tac-toe/'
      path: '/demo/tic-tac-toe'
      fullPath: '/demo/tic-tac-toe'
      preLoaderRoute: typeof DemoTicTacToeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/math/': {
      id: '/demo/math/'
      path: '/demo/math'
      fullPath: '/demo/math'
      preLoaderRoute: typeof DemoMathIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat/': {
      id: '/demo/chat/'
      path: '/demo/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHelloStreamRoute: ApiHelloStreamRoute,
  DemoChatIndexRoute: DemoChatIndexRoute,
  DemoMathIndexRoute: DemoMathIndexRoute,
  DemoTicTacToeIndexRoute: DemoTicTacToeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
