/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHelloStreamRouteImport } from './routes/api.hello-stream'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ChatTictactoeIndexRouteImport } from './routes/chat/tictactoe/index'
import { Route as ChatPlayTttIndexRouteImport } from './routes/chat/play-ttt/index'
import { Route as ChatMathIndexRouteImport } from './routes/chat/math/index'
import { Route as ChatFlightIndexRouteImport } from './routes/chat/flight/index'
import { Route as ChatCardsIndexRouteImport } from './routes/chat/cards/index'
import { Route as ChatBasicIndexRouteImport } from './routes/chat/basic/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloStreamRoute = ApiHelloStreamRouteImport.update({
  id: '/api/hello-stream',
  path: '/api/hello-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatTictactoeIndexRoute = ChatTictactoeIndexRouteImport.update({
  id: '/chat/tictactoe/',
  path: '/chat/tictactoe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPlayTttIndexRoute = ChatPlayTttIndexRouteImport.update({
  id: '/chat/play-ttt/',
  path: '/chat/play-ttt/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatMathIndexRoute = ChatMathIndexRouteImport.update({
  id: '/chat/math/',
  path: '/chat/math/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFlightIndexRoute = ChatFlightIndexRouteImport.update({
  id: '/chat/flight/',
  path: '/chat/flight/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCardsIndexRoute = ChatCardsIndexRouteImport.update({
  id: '/chat/cards/',
  path: '/chat/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBasicIndexRoute = ChatBasicIndexRouteImport.update({
  id: '/chat/basic/',
  path: '/chat/basic/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/chat/basic': typeof ChatBasicIndexRoute
  '/chat/cards': typeof ChatCardsIndexRoute
  '/chat/flight': typeof ChatFlightIndexRoute
  '/chat/math': typeof ChatMathIndexRoute
  '/chat/play-ttt': typeof ChatPlayTttIndexRoute
  '/chat/tictactoe': typeof ChatTictactoeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/chat/basic': typeof ChatBasicIndexRoute
  '/chat/cards': typeof ChatCardsIndexRoute
  '/chat/flight': typeof ChatFlightIndexRoute
  '/chat/math': typeof ChatMathIndexRoute
  '/chat/play-ttt': typeof ChatPlayTttIndexRoute
  '/chat/tictactoe': typeof ChatTictactoeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hello-stream': typeof ApiHelloStreamRoute
  '/chat/basic/': typeof ChatBasicIndexRoute
  '/chat/cards/': typeof ChatCardsIndexRoute
  '/chat/flight/': typeof ChatFlightIndexRoute
  '/chat/math/': typeof ChatMathIndexRoute
  '/chat/play-ttt/': typeof ChatPlayTttIndexRoute
  '/chat/tictactoe/': typeof ChatTictactoeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/chat/basic'
    | '/chat/cards'
    | '/chat/flight'
    | '/chat/math'
    | '/chat/play-ttt'
    | '/chat/tictactoe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/chat/basic'
    | '/chat/cards'
    | '/chat/flight'
    | '/chat/math'
    | '/chat/play-ttt'
    | '/chat/tictactoe'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/hello-stream'
    | '/chat/basic/'
    | '/chat/cards/'
    | '/chat/flight/'
    | '/chat/math/'
    | '/chat/play-ttt/'
    | '/chat/tictactoe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHelloStreamRoute: typeof ApiHelloStreamRoute
  ChatBasicIndexRoute: typeof ChatBasicIndexRoute
  ChatCardsIndexRoute: typeof ChatCardsIndexRoute
  ChatFlightIndexRoute: typeof ChatFlightIndexRoute
  ChatMathIndexRoute: typeof ChatMathIndexRoute
  ChatPlayTttIndexRoute: typeof ChatPlayTttIndexRoute
  ChatTictactoeIndexRoute: typeof ChatTictactoeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello-stream': {
      id: '/api/hello-stream'
      path: '/api/hello-stream'
      fullPath: '/api/hello-stream'
      preLoaderRoute: typeof ApiHelloStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/tictactoe/': {
      id: '/chat/tictactoe/'
      path: '/chat/tictactoe'
      fullPath: '/chat/tictactoe'
      preLoaderRoute: typeof ChatTictactoeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/play-ttt/': {
      id: '/chat/play-ttt/'
      path: '/chat/play-ttt'
      fullPath: '/chat/play-ttt'
      preLoaderRoute: typeof ChatPlayTttIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/math/': {
      id: '/chat/math/'
      path: '/chat/math'
      fullPath: '/chat/math'
      preLoaderRoute: typeof ChatMathIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/flight/': {
      id: '/chat/flight/'
      path: '/chat/flight'
      fullPath: '/chat/flight'
      preLoaderRoute: typeof ChatFlightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/cards/': {
      id: '/chat/cards/'
      path: '/chat/cards'
      fullPath: '/chat/cards'
      preLoaderRoute: typeof ChatCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/basic/': {
      id: '/chat/basic/'
      path: '/chat/basic'
      fullPath: '/chat/basic'
      preLoaderRoute: typeof ChatBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHelloStreamRoute: ApiHelloStreamRoute,
  ChatBasicIndexRoute: ChatBasicIndexRoute,
  ChatCardsIndexRoute: ChatCardsIndexRoute,
  ChatFlightIndexRoute: ChatFlightIndexRoute,
  ChatMathIndexRoute: ChatMathIndexRoute,
  ChatPlayTttIndexRoute: ChatPlayTttIndexRoute,
  ChatTictactoeIndexRoute: ChatTictactoeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
