/**
 * AgentCore Tool Registry (auto-generated)
 *
 * DO NOT EDIT - This file is generated by @sweatpants/framework
 * Regenerate by modifying files in src/tools/ or AgentCore support config.
 *
 * This registry is intended for AgentCore Runtime packaging. It imports only
 * the explicitly supported Batch-1 MCP bridge-compatible tools. Canonical names
 * are intrinsic MCP tool names; generated app-facing names are aliases.
 */

import { bookFlightTool } from '../tools/book-flight/tool'
import { playTttTool } from '../tools/play-ttt/tool'
import { tictactoeTool } from '../tools/tictactoe/tool'

export interface AgentCoreToolRegistryEntry {
  /** Canonical intrinsic MCP tool name used by the runtime. */
  name: string
  /** Actual finalized tool object to execute. */
  tool: unknown
  /** Additional app/runtime names that should resolve to this tool. */
  aliases?: string[]
}

export const agentCoreToolRegistry: AgentCoreToolRegistryEntry[] = [
  {
    name: 'book_flight',
    tool: bookFlightTool,
    aliases: ["book-flight_book_flight"],
  },
  {
    name: 'play_ttt',
    tool: playTttTool,
    aliases: ["play-ttt_play_ttt"],
  },
  {
    name: 'tictactoe',
    tool: tictactoeTool,
    aliases: ["tictactoe_tictactoe"],
  },
] satisfies AgentCoreToolRegistryEntry[]

export const agentCoreToolList: unknown[] = agentCoreToolRegistry.map((entry) => entry.tool)
export const agentCoreToolNames: string[] = agentCoreToolRegistry.map((entry) => entry.name)
export const agentCoreToolAliases: ReadonlyMap<string, string> = new Map<string, string>([
  ['book_flight', 'book_flight'],
  ['book-flight_book_flight', 'book_flight'],
  ['play_ttt', 'play_ttt'],
  ['play-ttt_play_ttt', 'play_ttt'],
  ['tictactoe', 'tictactoe'],
  ['tictactoe_tictactoe', 'tictactoe'],
])

export function normalizeAgentCoreToolName(name: string): string | undefined {
  return agentCoreToolAliases.get(name)
}

export function normalizeAgentCoreToolNames(names: string[]): string[] {
  const normalized = names.map((name) => normalizeAgentCoreToolName(name)).filter((name): name is string => typeof name === 'string')
  return Array.from(new Set(normalized)).sort()
}

export function unsupportedAgentCoreToolNames(names: string[]): string[] {
  return names.filter((name) => !agentCoreToolAliases.has(name))
}

export function getAgentCoreTool(name: string): unknown | undefined {
  const canonicalName = normalizeAgentCoreToolName(name)
  if (!canonicalName) return undefined
  return agentCoreToolRegistry.find((entry) => entry.name === canonicalName)?.tool
}
