/**
 * Tool Worker Entry (auto-generated)
 *
 * DO NOT EDIT - This file is generated by @sweatpants/framework
 */
 import { runWorker, createWorkerToolRegistry } from '@sweatpants/tool-runtime-local/worker'

import { bookFlightTool } from '../tools/book-flight/tool.ts'
import { calculator } from '../tools/calculator.ts'
import { playTttTool } from '../tools/play-ttt/tool.ts'
import { tictactoeTool } from '../tools/tictactoe/tool.ts'

const registry = createWorkerToolRegistry([
  { name: 'book-flight_book_flight', handler: function* (params, ctx) {
    const tool = bookFlightTool
    if (tool && typeof tool === 'object') {
      if ('execute' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).execute(params, ctx)
      }
      if ('handoffConfig' in (tool as unknown as Record<string, unknown>)) {
        const config = (tool as any).handoffConfig
        const handoff = yield* config.before(params, ctx)
        const clientResult = yield* config.client(handoff, ctx)
        return yield* config.after(handoff, clientResult, ctx, params)
      }
      if ('server' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).server(params, ctx)
      }
    }
    return yield* (tool as any)(params, ctx)
  } },
  { name: 'calculator', handler: function* (params, ctx) {
    const tool = calculator
    if (tool && typeof tool === 'object') {
      if ('execute' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).execute(params, ctx)
      }
      if ('handoffConfig' in (tool as unknown as Record<string, unknown>)) {
        const config = (tool as any).handoffConfig
        const handoff = yield* config.before(params, ctx)
        const clientResult = yield* config.client(handoff, ctx)
        return yield* config.after(handoff, clientResult, ctx, params)
      }
      if ('server' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).server(params, ctx)
      }
    }
    return yield* (tool as any)(params, ctx)
  } },
  { name: 'play-ttt_play_ttt', handler: function* (params, ctx) {
    const tool = playTttTool
    if (tool && typeof tool === 'object') {
      if ('execute' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).execute(params, ctx)
      }
      if ('handoffConfig' in (tool as unknown as Record<string, unknown>)) {
        const config = (tool as any).handoffConfig
        const handoff = yield* config.before(params, ctx)
        const clientResult = yield* config.client(handoff, ctx)
        return yield* config.after(handoff, clientResult, ctx, params)
      }
      if ('server' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).server(params, ctx)
      }
    }
    return yield* (tool as any)(params, ctx)
  } },
  { name: 'tictactoe_tictactoe', handler: function* (params, ctx) {
    const tool = tictactoeTool
    if (tool && typeof tool === 'object') {
      if ('execute' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).execute(params, ctx)
      }
      if ('handoffConfig' in (tool as unknown as Record<string, unknown>)) {
        const config = (tool as any).handoffConfig
        const handoff = yield* config.before(params, ctx)
        const clientResult = yield* config.client(handoff, ctx)
        return yield* config.after(handoff, clientResult, ctx, params)
      }
      if ('server' in (tool as unknown as Record<string, unknown>)) {
        return yield* (tool as any).server(params, ctx)
      }
    }
    return yield* (tool as any)(params, ctx)
  } }
])

runWorker(registry)
