/**
 * Tool Registry (auto-generated)
 *
 * DO NOT EDIT - This file is generated by @tanstack/framework
 * Regenerate by modifying files in src/tools/
 */

import { askQuestion } from '../tools/general/ask_question'
import { calculator } from '../tools/calculator'

/**
 * All discovered tools as a const object.
 * Use this for type-safe tool access.
 */
export const tools = {
  askQuestion,
  calculator,
} as const

/**
 * Array of all tools (for runtime iteration).
 */
export const toolList = Object.values(tools)

/**
 * Union type of all tool names.
 */
export type ToolName =
  | 'ask_question'
  | 'calculator'

/**
 * Get a tool by name (type-safe).
 */
export function getTool<T extends ToolName>(name: T) {
  return toolList.find((t) => t.name === name)
}

/**
 * Type helper: Extract the tool type by name.
 */
export type ToolByName<T extends ToolName> = (typeof tools)[keyof typeof tools] & { name: T }
