/**
 * Tool Worker Entry (auto-generated)
 *
 * DO NOT EDIT - This file is generated by @sweatpants/framework
 */
import { runToolWorker } from '@sweatpants/core/transport/worker'

import { calculator } from '../tools/calculator'
import { startTttGame } from '../tools/games/tic-tac-toe'
import { tttMove } from '../tools/games/tic-tac-toe'
import { tttWinner } from '../tools/games/tic-tac-toe'
import { askQuestion } from '../tools/general/ask_question'
import { pickCard } from '../tools/pick-card'

const toolLoaders: Record<string, () => unknown> = {
  'calculator': () => calculator,
  'games_start_ttt_game': () => startTttGame,
  'games_ttt_move': () => tttMove,
  'games_ttt_winner': () => tttWinner,
  'general_ask_question': () => askQuestion,
  'pick_card': () => pickCard
}

runToolWorker(function* (initData, ctx) {
  const loader = toolLoaders[initData.toolName]
  if (!loader) {
    throw new Error(`Unknown tool: ${initData.toolName}`)
  }

  const tool = loader()
  if (tool && typeof tool === 'object') {
    if ('execute' in (tool as Record<string, unknown>)) {
      return yield* (tool as any).execute(initData.params, ctx)
    }
    if ('server' in (tool as Record<string, unknown>)) {
      return yield* (tool as any).server(initData.params, ctx)
    }
  }

  return yield* (tool as any)(initData.params, ctx)
})
