/**
 * Transport API
 *
 * A unified transport API with type-inferred initialization.
 *
 * ## Usage
 *
 * ```typescript
 * const [MemoryPrincipal, MemoryOperative] = MemoryPair();
 *
 * // Principal side - returns { send, request, stream }
 * const principal = yield* initTransport(MemoryPrincipal());
 * const response = yield* principal.request({ kind: "elicit", ... });
 *
 * // Operative side - returns { send, stream }
 * const operative = yield* initTransport(MemoryOperative());
 * for (const req of yield* each(yield* operative.stream())) {
 *   yield* operative.send({ type: "response", ... });
 *   yield* each.next();
 * }
 * ```
 *
 * @packageDocumentation
 */

import { createApi } from "effection/experimental";
import type { Operation, Stream } from "effection";
import type {
  PrincipalOutgoing,
  PrincipalIncoming,
  OperativeOutgoing,
  OperativeIncoming,
  TransportRequest,
  RequestKind,
  ResponseByKind,
} from "../types/transport.ts";

// =============================================================================
// ERROR TYPES
// =============================================================================

/**
 * Error thrown by transport operations.
 */
export class TransportError extends Error {
  constructor(
    message: string,
    public code: TransportErrorCode
  ) {
    super(message);
    this.name = "TransportError";
  }
}

/**
 * Transport error codes.
 */
export type TransportErrorCode =
  | "NOT_CONFIGURED"
  | "DISCONNECTED"
  | "TIMEOUT";

// =============================================================================
// REQUEST TYPES
// =============================================================================

/**
 * Request without ID - ID is generated by request() internally.
 */
export type TransportRequestWithoutId<K extends RequestKind = RequestKind> = Omit<
  TransportRequest<K>,
  "id"
>;

// =============================================================================
// MIDDLEWARE TYPES
// =============================================================================

/**
 * Middleware function signature matching Effection's Decorate pattern.
 */
export type MiddlewareFn<TArgs extends unknown[], TReturn> = (
  args: TArgs,
  next: (...args: TArgs) => Operation<TReturn>
) => Operation<TReturn>;

// Message type for send (union of both directions)
type SendMessage = PrincipalOutgoing | OperativeOutgoing;

// Stream return type (union of both directions)
type StreamReturn = Stream<PrincipalIncoming | OperativeIncoming, void>;

/**
 * Principal middleware - includes send, request, and stream.
 */
export interface PrincipalMiddleware {
  send: MiddlewareFn<[SendMessage], void>;
  request: MiddlewareFn<[TransportRequestWithoutId], ResponseByKind[RequestKind]>;
  stream: MiddlewareFn<[], StreamReturn>;
}

/**
 * Operative middleware - includes send and stream (no request).
 */
export interface OperativeMiddleware {
  send: MiddlewareFn<[SendMessage], void>;
  stream: MiddlewareFn<[], StreamReturn>;
}

/**
 * Union of middleware types.
 */
export type TransportMiddleware = PrincipalMiddleware | OperativeMiddleware;

// =============================================================================
// TYPED TRANSPORT INTERFACES
// =============================================================================

/**
 * Principal transport interface (agent side).
 * Has send, request (with correlation), and stream.
 */
export interface PrincipalTransportApi {
  send(message: PrincipalOutgoing): Operation<void>;
  request<K extends RequestKind>(req: TransportRequestWithoutId<K>): Operation<ResponseByKind[K]>;
  stream(): Operation<Stream<PrincipalIncoming, void>>;
}

/**
 * Operative transport interface (UI side).
 * Has send and stream (no request).
 */
export interface OperativeTransportApi {
  send(message: OperativeOutgoing): Operation<void>;
  stream(): Operation<Stream<OperativeIncoming, void>>;
}

// =============================================================================
// TRANSPORT API
// =============================================================================

/**
 * The unified Transport API.
 * Decorated by middleware via initTransport().
 */
export const TransportApi = createApi("transport", {
  send(_message: PrincipalOutgoing | OperativeOutgoing): Operation<void> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },

  request<K extends RequestKind>(
    _req: TransportRequestWithoutId<K>
  ): Operation<ResponseByKind[K]> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },

  stream(): Operation<Stream<PrincipalIncoming | OperativeIncoming, void>> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },
});

// =============================================================================
// INIT TRANSPORT
// =============================================================================

/**
 * Initialize the transport with middleware and return a typed interface.
 * 
 * The return type is inferred from the middleware:
 * - PrincipalMiddleware → PrincipalTransportApi (send, request, stream)
 * - OperativeMiddleware → OperativeTransportApi (send, stream)
 *
 * @example
 * ```typescript
 * const [MemoryPrincipal, MemoryOperative] = MemoryPair();
 *
 * // Principal - has request()
 * const principal = yield* initTransport(MemoryPrincipal());
 * const response = yield* principal.request({ kind: "elicit", ... });
 *
 * // Operative - no request()
 * const operative = yield* initTransport(MemoryOperative());
 * ```
 */
export function initTransport(
  middleware: Operation<PrincipalMiddleware>
): Operation<PrincipalTransportApi>;
export function initTransport(
  middleware: Operation<OperativeMiddleware>
): Operation<OperativeTransportApi>;
export function* initTransport(
  middleware: Operation<TransportMiddleware>
): Operation<PrincipalTransportApi | OperativeTransportApi> {
  const decorations = yield* middleware;
  yield* TransportApi.decorate(decorations);

  const { send, request, stream } = TransportApi.operations;

  if ("request" in decorations) {
    return {
      send: send as PrincipalTransportApi["send"],
      request: request as PrincipalTransportApi["request"],
      stream: stream as PrincipalTransportApi["stream"],
    };
  } else {
    return {
      send: send as OperativeTransportApi["send"],
      stream: stream as OperativeTransportApi["stream"],
    };
  }
}

// =============================================================================
// CONVENIENCE ACCESSORS
// =============================================================================

/**
 * Get the principal transport interface.
 * Use this when transport is already initialized elsewhere.
 *
 * @example
 * ```typescript
 * // In agent code, after transport is initialized
 * const { send, request, stream } = yield* usePrincipal();
 * ```
 */
export function* usePrincipal(): Operation<PrincipalTransportApi> {
  const { send, request, stream } = TransportApi.operations;
  return {
    send: send as PrincipalTransportApi["send"],
    request: request as PrincipalTransportApi["request"],
    stream: stream as PrincipalTransportApi["stream"],
  };
}

/**
 * Get the operative transport interface.
 * Use this when transport is already initialized elsewhere.
 *
 * @example
 * ```typescript
 * // In UI code, after transport is initialized
 * const { send, stream } = yield* useOperative();
 * ```
 */
export function* useOperative(): Operation<OperativeTransportApi> {
  const { send, stream } = TransportApi.operations;
  return {
    send: send as OperativeTransportApi["send"],
    stream: stream as OperativeTransportApi["stream"],
  };
}

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Generate a unique request ID.
 */
export function generateRequestId(prefix = "req"): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).slice(2, 8);
  return `${prefix}_${timestamp}_${random}`;
}
