/**
 * Transport API
 *
 * A unified transport API using Effection's decoration pattern.
 *
 * ## Usage
 *
 * ```typescript
 * const [MemoryPrincipal, MemoryOperative] = MemoryPair();
 *
 * // Principal side - decorate and use operations
 * yield* TransportApi.decorate(yield* MemoryPrincipal());
 * const { send, request, stream } = yield* usePrincipal();
 * const response = yield* request({ kind: "elicit", ... });
 *
 * // Operative side - decorate and use operations
 * yield* TransportApi.decorate(yield* MemoryOperative());
 * const { send, stream } = yield* useOperative();
 * for (const req of yield* each(yield* stream())) {
 *   yield* send({ type: "response", ... });
 *   yield* each.next();
 * }
 * ```
 *
 * @packageDocumentation
 */

import { createApi } from "effection/experimental";
import type { Operation, Stream } from "effection";
import type {
  PrincipalOutgoing,
  PrincipalIncoming,
  OperativeOutgoing,
  OperativeIncoming,
  TransportRequest,
  RequestKind,
  ResponseByKind,
} from "../types/transport.ts";

// =============================================================================
// ERROR TYPES
// =============================================================================

/**
 * Error thrown by transport operations.
 */
export class TransportError extends Error {
  constructor(
    message: string,
    public code: TransportErrorCode
  ) {
    super(message);
    this.name = "TransportError";
  }
}

/**
 * Transport error codes.
 */
export type TransportErrorCode =
  | "NOT_CONFIGURED"
  | "DISCONNECTED"
  | "TIMEOUT";

// =============================================================================
// REQUEST TYPES
// =============================================================================

/**
 * Request without ID - ID is generated by request() internally.
 */
export type TransportRequestWithoutId<K extends RequestKind = RequestKind> = Omit<
  TransportRequest<K>,
  "id"
>;

// =============================================================================
// MIDDLEWARE TYPES
// =============================================================================

/**
 * Middleware function signature matching Effection's Decorate pattern.
 */
export type MiddlewareFn<TArgs extends unknown[], TReturn> = (
  args: TArgs,
  next: (...args: TArgs) => Operation<TReturn>
) => Operation<TReturn>;

// Message type for send (union of both directions)
type SendMessage = PrincipalOutgoing | OperativeOutgoing;

// Stream return type (union of both directions)
type StreamReturn = Stream<PrincipalIncoming | OperativeIncoming, void>;

/**
 * Transport middleware decoration object.
 * 
 * Middleware can implement any subset of these operations.
 * - send: Send a message through the transport
 * - request: Send a request and wait for correlated response (principal only)
 * - stream: Get the incoming message stream
 */
export interface TransportMiddleware {
  send?: MiddlewareFn<[SendMessage], void>;
  request?: MiddlewareFn<[TransportRequestWithoutId], ResponseByKind[RequestKind]>;
  stream?: MiddlewareFn<[], StreamReturn>;
}

// =============================================================================
// TYPED TRANSPORT INTERFACES
// =============================================================================

/**
 * Principal transport interface (agent side).
 * Has send, request (with correlation), and stream.
 */
export interface PrincipalTransportApi {
  send(message: PrincipalOutgoing): Operation<void>;
  request<K extends RequestKind>(req: TransportRequestWithoutId<K>): Operation<ResponseByKind[K]>;
  stream(): Operation<Stream<PrincipalIncoming, void>>;
}

/**
 * Operative transport interface (UI side).
 * Has send and stream (no request).
 */
export interface OperativeTransportApi {
  send(message: OperativeOutgoing): Operation<void>;
  stream(): Operation<Stream<OperativeIncoming, void>>;
}

// =============================================================================
// TRANSPORT API
// =============================================================================

/**
 * The unified Transport API.
 * 
 * Decorate this API with transport middleware to provide implementations.
 * 
 * @example
 * ```typescript
 * // Decorate with middleware
 * yield* TransportApi.decorate(yield* MemoryPrincipal());
 * 
 * // Use operations
 * yield* TransportApi.operations.send(message);
 * const response = yield* TransportApi.operations.request({ kind: "elicit", ... });
 * ```
 */
export const TransportApi = createApi("transport", {
  send(_message: PrincipalOutgoing | OperativeOutgoing): Operation<void> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },

  request<K extends RequestKind>(
    _req: TransportRequestWithoutId<K>
  ): Operation<ResponseByKind[K]> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },

  stream(): Operation<Stream<PrincipalIncoming | OperativeIncoming, void>> {
    throw new TransportError("No transport configured", "NOT_CONFIGURED");
  },
});

// =============================================================================
// CONVENIENCE ACCESSORS
// =============================================================================

/**
 * Get the principal transport interface.
 * Use this when transport is already decorated in the current scope.
 *
 * @example
 * ```typescript
 * yield* TransportApi.decorate(yield* MemoryPrincipal());
 * const { send, request, stream } = yield* usePrincipal();
 * const response = yield* request({ kind: "elicit", ... });
 * ```
 */
export function* usePrincipal(): Operation<PrincipalTransportApi> {
  const { send, request, stream } = TransportApi.operations;
  return {
    send: send as PrincipalTransportApi["send"],
    request: request as PrincipalTransportApi["request"],
    stream: stream as PrincipalTransportApi["stream"],
  };
}

/**
 * Get the operative transport interface.
 * Use this when transport is already decorated in the current scope.
 *
 * @example
 * ```typescript
 * yield* TransportApi.decorate(yield* MemoryOperative());
 * const { send, stream } = yield* useOperative();
 * ```
 */
export function* useOperative(): Operation<OperativeTransportApi> {
  const { send, stream } = TransportApi.operations;
  return {
    send: send as OperativeTransportApi["send"],
    stream: stream as OperativeTransportApi["stream"],
  };
}

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Generate a unique request ID.
 */
export function generateRequestId(prefix = "req"): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).slice(2, 8);
  return `${prefix}_${timestamp}_${random}`;
}
